CREATE DATABASE [QLSACH_Tiki]
GO
USE QLSACH_Tiki
GO
CREATE TABLE dbo.LOAISACH (
	MALOAISACH VARCHAR(5) NOT NULL,
	LOAISACH nvarchar(30) NOT NULL,
	CONSTRAINT [PK_LOAISACH] PRIMARY KEY CLUSTERED
	(
		MALOAISACH ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF )
) ON [PRIMARY]
GO
ALTER TABLE dbo.LOAISACH ADD CONSTRAINT LOAISACH_LOAISACH_U UNIQUE (LOAISACH)
GO 
INSERT dbo.LOAISACH
        ( MALOAISACH, LOAISACH )
VALUES  ( 'L501', -- MALOAISACH - varchar(5)
          N'SÁCH TƯ DUY KĨ NĂNG SỐNG'  -- LOAISACH - nvarchar(30)
          )
INSERT dbo.LOAISACH
        ( MALOAISACH, LOAISACH )
VALUES  ( 'L502', -- MALOAISACH - varchar(5)
          N'SÁCH THIẾU NHI'  -- LOAISACH - nvarchar(30)
          )
INSERT dbo.LOAISACH
        ( MALOAISACH, LOAISACH )
VALUES  ( 'L503', -- MALOAISACH - varchar(5)
          N'SÁCH KINH TẾ'  -- LOAISACH - nvarchar(30)
          )
INSERT dbo.LOAISACH
        ( MALOAISACH, LOAISACH )
VALUES  ( 'L504', -- MALOAISACH - varchar(5)
          N'SÁCH CÔNG NGHỆ THÔNG TIN'  -- LOAISACH - nvarchar(30)
          )

CREATE TABLE dbo.[TACGIA] (
	MATACGIA VARCHAR(5) NOT NULL,
	TENTACGIA NVARCHAR(40) NOT NULL,
	CONSTRAINT [PK_TACGIA] PRIMARY KEY CLUSTERED
	(
		MATACGIA ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF )
) ON [PRIMARY]
GO
ALTER TABLE dbo.TACGIA ADD CONSTRAINT TACGIA_TENTACGIA_U UNIQUE (TENTACGIA)
GO
INSERT dbo.TACGIA
        ( MATACGIA, TENTACGIA )
VALUES  ( 'TG001', -- MATACGIA - varchar(5)
          N'Spencer Johnson'  -- TENTACGIA - nvarchar(40)
          )
INSERT dbo.TACGIA
        ( MATACGIA, TENTACGIA )
VALUES  ( 'TG002', -- MATACGIA - varchar(5)
          N'Cảnh Thiên'  -- TENTACGIA - nvarchar(40)
          )
INSERT dbo.TACGIA
        ( MATACGIA, TENTACGIA )
VALUES  ( 'TG003', -- MATACGIA - varchar(5)
          N'Phạm Văn Ất'  -- TENTACGIA - nvarchar(40)
          )
INSERT dbo.TACGIA
        ( MATACGIA, TENTACGIA )
VALUES  ( 'TG004', -- MATACGIA - varchar(5)
          N'Trần Đan Thư'  -- TENTACGIA - nvarchar(40)
          )
INSERT dbo.TACGIA
        ( MATACGIA, TENTACGIA )
VALUES  ( 'TG005', -- MATACGIA - varchar(5)
          N'Phạm Quang Huy'  -- TENTACGIA - nvarchar(40)
          )
CREATE TABLE dbo.SACH (
	MASACH VARCHAR(5) NOT NULL,
	TENSACH NVARCHAR(100) NOT NULL,
	MATACGIA VARCHAR(5) NOT NULL,
	MALOAISACH VARCHAR(5) NOT NULL,
	HINHANH NVARCHAR(150) NOT NULL,
	GIATIEN INT NOT NULL,
	SOLUONG TINYINT NOT NULL,
	NGAYXUATBAN DATE,
	KICHTHUOC VARCHAR(15),
	SOTRANG INT,
	SKU BIGINT NOT NULL,
	MOTA NTEXT NOT NULL,
	CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED
	(
		MASACH ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = OFF )
) ON [PRIMARY]
GO
ALTER TABLE SACH ADD CONSTRAINT SACH_TENSACH_U UNIQUE (TENSACH)
GO
